### PR TITLE
KAZ ADM2 Metadata Validation

### PR DESCRIPTION
**Pull request by kpupkiewicz**
## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by kpupkiewicz** [comment]
responding to issue #462

**Review by slfuhrig — CHANGES_REQUESTED** [review]
So close!! Please delete the ISO_Code field (since this is ADM2) and see if you can find roman alphabet names. Let us know if you have trouble with the names.

**Review by slfuhrig — APPROVED** [review]
Perfect!

**Comment by slfuhrig** [comment]
closes #462

**Comment by DanRunfola** [comment]
:kazakhstan:

**Pull request merged**
