### PR TITLE
Re-adding the zip file

### PR DESCRIPTION
**Pull request by MichaelR-geoLab**
issue #253 the files were in a nested folder, so I changed that so they are now in the root.

## Checklist:

- [ ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [ ] I have included a file named "meta.txt", with all required metadata (see an example at https://github.com/wmgeolab/gbRelease/blob/master/sourceData/gbOpen/AGO_ADM1.zip).
- [ ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.

### CODE REVIEW

**Comment by DanRunfola** [comment]
I think this is actually good to go - I need to update our bot :).  Give me a few minutes.

**Comment by DanRunfola** [comment]
Yay!  Just had to do a bit of bot brain surgery.  On to the human review.

**Review by slfuhrig — APPROVED** [review]
Great job!

**Review by sylviashea1 — APPROVED** [review]
Everything looks good! Nice job.

**Pull request merged**
