### PR TITLE
NER ADM0

### PR DESCRIPTION
**Pull request by jdturner303**
## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Make sure to change the release type to whatever matches the location of the file you're working on. In this case it's "gbHumanitarian."

**Comment by jdturner303** [comment]
@slfuhrig Okay. First, where do I change the release type. Also, will doing so fix the pull request check error? 
Screen Shot 2020-10-19 at 4 04 09 PM

**Comment by slfuhrig** [comment]
James, change the release type in the metadata (it's a field), and that will likely correct the error.

**Comment by DanRunfola** [comment]
Continued in #367

**Comment by DanRunfola** [comment]
@all-contributors please add @jdturner303  for data

**Pull request closed without merging**
