### PR TITLE
MKD ADM2 Metadata Validation

### PR DESCRIPTION
**Pull request by kpupkiewicz**
#469

## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by nmspage — CHANGES_REQUESTED** [review]
Everything looks good except there is are extra "Shape_1" and "ID" fields in the attribute table

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Almost there! Please see if you can remove "Shape" and "ID" from the attribute table.

**Review by slfuhrig — APPROVED** [review]
Perfect!

**Comment by slfuhrig** [comment]
closes #469

**Comment by slfuhrig** [comment]
Everything looks great on my end. Will have @nmspage review again once work resumes for the semester.

**Review by nmspage — APPROVED** [review]

**Comment by DanRunfola** [comment]
Beautiful, thanks all for this one.

**Pull request merged**
