### PR TITLE
FSM ADM 2 - #398

### PR DESCRIPTION
**Pull request by slfuhrig**
## Checklist:

- [ x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [ x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [ x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by sylviashea1 — CHANGES_REQUESTED** [review]
The name field in the attribute table is "name" instead of "Name". Not sure if that matters. If not, everything else is good and ready 2 merge.

**Review by nmspage — APPROVED** [review]
Awesome!!

**Comment by slfuhrig** [comment]
Please take a look at this before it closes @sylviashea1

**Review by sylviashea1 — APPROVED** [review]
Everything looks good!

**Comment by DanRunfola** [comment]
I just merged this one in, but as a note we'll probably want to revisit to get a more accurate layer "in the future".  This looks like it includes water rights, and we're aiming for terrestrial. Going to, of course, be hard in these cases.

**Pull request merged**
