### PR TITLE
ESP_ADM3 gbOpen LFS attempt

### PR DESCRIPTION
**Pull request by nmspage**
This is an attempt at editing .gitattributes as well

## Why do we need this boundary?  
 #128 #691 

## Anything Unusual?
 It is possible that I will not be able to edit the .gitattributes because the bot may see me as a threat, I guess I'm just too advanced for his small brain to compute

## Checklist:

- [x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by nmspage** [comment]
I edited the metadata and found the license source that is acceptable for gbOpen

**Review by slfuhrig — APPROVED** [review]
Looks great!

**Comment by slfuhrig** [comment]
closes #128

**Review by slfuhrig — APPROVED** [review]

**Review by slfuhrig — CHANGES_REQUESTED** [review]
You're failing because some of the CHL files are labeled for gB Auth, so please change the metadata to match gB OPEN -- a separate PR is needed to upload them to Auth.

**Review by slfuhrig — APPROVED** [review]
Great job removing extra files.

**Review by DanRunfola — CHANGES_REQUESTED** [review]
I am confused :)

The version of this PR i am looking at has both CHL_ADM3 and ESP_ADM3 in it - which is fine, but I'm not sure what issues this closes.  Before I accept, I wanted to get one more check. @sylviashea1 @slfuhrig

**Comment by slfuhrig** [comment]
closes #128 and #777 @DanRunfola

**Pull request closed without merging**
