### PR TITLE
STP_ADM2

### PR DESCRIPTION
**Pull request by dorianvmiller**
metadata validation for STP_ADM2

## Why do we need this boundary?  
 #440 

## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by nmspage — CHANGES_REQUESTED** [review]
Along with the "Name" field, it looks as though there's a visible discrepancy between ADM2 and ADM0, an island to the south is missing from this shapefile. Easy fix though! Could you take the ADM0 layer, use the "explode" and add the island to ADM2? Should be easy to look up the name of the island. Let me know if you have questions!

**Comment by dorianvmiller** [comment]
Good catch! I added the island from the ADM0 layer - turns out it's a part of one of the districts already in the ADM2 layer so I merged them together (Caué in the attribute table). Let me know if anything else needs to be changed!

**Review by nmspage — APPROVED** [review]
Awesome thanks!!

**Review by nmspage — CHANGES_REQUESTED** [review]
My mistake in forgetting this earlier - I realized that we need to change source 1 in the metadata to geoBoundaries because of the edits. Please also add that there were geometry changes in the notes. Source 2 becomes the old source 1. Thank you!

**Review by nmspage — APPROVED** [review]
Perfect, thank you!

**Comment by DanRunfola** [comment]
Thank you!

**Pull request merged**
