### PR TITLE
NER_ADM0

### PR DESCRIPTION
**Pull request by jdturner303**
gbHumanitarian

## Checklist:

- [x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — APPROVED** [review]
Great work!

**Comment by jdturner303** [comment]
thank you! I believe that I didn't tag the issue number #333 . Thus the issue still exists in my issues. Where should I tag the issues moving forward and can I still do it for this one?

**Comment by slfuhrig** [comment]
I usually take care of linking issues and PRs, so don't worry about that. Just work on the next issue.

**Comment by DanRunfola** [comment]
Thank you for the contribution - very helpful. :100:

**Pull request merged**
