### PR TITLE
NGA_ADM1 Open

### PR DESCRIPTION
**Pull request by larogersWM**
I replaced the old NGA_ADM1 zip file with my new NGA_ADM1 zip file. (#112)

### CODE REVIEW

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Hi Lindsey,

Great work! Just a couple small comments -
1) Can you go back to your shapefile and add ADM 1 ISO Codes? They're usually the two letter national ISO (NG here I think) followed by a dash and the unique code for each polygon. Here's the link: https://www.iso.org/obp/ui/#iso:code:3166:NG

2) Can you reupload your metadata sheet as a ".csv" instead of a numbers file? I can't open numbers on my computer, so once it's converted I'll look it over.

Let us know if you have any questions.

**Comment by DanRunfola** [comment]
Looks like you uplaoded it as the mac numbers file type :)

**Review by slfuhrig — APPROVED** [review]
Thanks for making the changes!

**Review by slfuhrig — APPROVED** [review]

**Comment by DanRunfola** [comment]
@all-contributors please add @larogersWM for data

**Comment by DanRunfola** [comment]
@all-contributors please add @larogersWM  for data

**Pull request merged**
