### PR TITLE
MDA_ADM1

### PR DESCRIPTION
**Pull request by dorianvmiller**
Metadata validation for ADM_ADM1 (#503)

## Why do we need this boundary?  
 https://github.com/wmgeolab/gbRelease/issues/503

## Checklist:

- [ x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [ x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [ x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [ x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by sylviashea1** [comment]
Bot states that MDA is not a valid ISO code, but is listed as an acceptable input in the csv.

**Comment by slfuhrig** [comment]
Also failing ISO @DanRunfola

**Review by slfuhrig — APPROVED** [review]
Everything looks perfect, but there appear to be 2 files changed here... Not sure if we can merge it. @DanRunfola

**Comment by DanRunfola** [comment]
@dorianvmiller @slfuhrig I had to revert this - I didn't catch the spelling issue (MDA_ADM vs. MDA_**AMD**).  Will need a new PR.  Sorry :-1:

**Pull request merged**
