### PR TITLE
CIV Shapefile ADM0 Open Source Issue #77

### PR DESCRIPTION
**Pull request by memulder**
Issue #77 Found shapefile from Natural Earth with open source license for Cote d'Ivoire ADM 0 (CIV ADM0). Original shapefile had all ADM 0s for all countries so CIV was queried out seperately.

### CODE REVIEW

**Review by slfuhrig — APPROVED** [review]
Great work as always!

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Would you mind removing the ISO field from FRA_ADM5? Thanks for updating the metadata for it!

**Review by slfuhrig — APPROVED** [review]
Thanks for making the changes.

**Review by DanRunfola — CHANGES_REQUESTED** [review]
Ok!  This is looking close.  I made a few edits, and wanted to ask you to re-commit so that this can work with the new metadata system (no more csv to edit!).
1) Download both this zip file and the zip file I sent you on slack (for France - it was 300 megs or so, so couldn't do it here):
[CIV_ADM0.zip](https://github.com/wmgeolab/gbRelease/files/5271413/CIV_ADM0.zip)

2) Replace the zips in your local copy of geoboundaries with those two zips.  Please open them and take a look at the meta.txt files to make sure I got it right!

3) Delete your gbOpenMetaData.csv - shouldn't need this anymore.

4) add and commit your git changes as usual.

5) That should trigger a new auto-checking thing here!

**Review by DanRunfola — APPROVED** [review]

**Review by DanRunfola — CHANGES_REQUESTED** [review]
Ok - all the automated tests are working, and everything checked out except:
1) CIV ADM0 - Projection is wrong.  Currently epsg:3395, needs to be WGS84 (EPSG 4326)
2) France ADM0 - Same thing. The file has a projection of: epsg:3395 ; needs to be WGS84 / EPSG 4326

**Comment by DanRunfola** [comment]
Hey Maddy -
Sorry about this, but we did some big updates on our scripts to make submissions easier in the future.  Could you do one of the below:
1) Submit your file through the web interface - see https://youtu.be/9v5bZcpUx3I

or

2a) On your local client, Click on the 'current branch' tab and first select 'master' as the current branch (if it's not already selected).
2b)  Click on the 'fetch origin' button.
2c) Click on the 'current branch' tab again and click the 'choose a branch to merge into master' button at the bottom.
2d) Select upstream/master from this list, and this pull the changes down from the master repository to bring your local clone up to date.

Then, push your files back to this PR.  That will trigger the new checks, and make it so all your future desktop-based checks will work. Approach (1) is hopefully a much easier alternative (and why we did the upgrades).

**Comment by slfuhrig** [comment]
One thing that may not show up on the checks but needs to be fixed is that you don't have a canonical (local) name listed.

**Comment by DanRunfola** [comment]
Closing this as it is now being covered in pr https://github.com/wmgeolab/gbRelease/pull/254

**Comment by DanRunfola** [comment]
@all-contributors please add @memulder  for data

**Pull request closed without merging**
