### PR TITLE
Issue #139 Shapefile reupload

### PR DESCRIPTION
**Pull request by MichaelR-geoLab**
Re uploaded new shapefile with open license this time, and added it to the metadata spreadsheet.

### CODE REVIEW

**Review by DanRunfola — CHANGES_REQUESTED** [review]
Hey Michael!

Two issues before we can accept this (at least, I have not reviewed the zip file shape yet).

1) You need to remove the ".shp" file that I think you left behind (we just need the zip with everything in it).
2) IN the gbOpenMetaData.csv, you left the older ADM2.  You will need to remove that record, as your new shapefile will be replacing it in the gbOpen release!

**Review by DanRunfola — CHANGES_REQUESTED** [review]
One other update on this - it is possible we need to *rename* the old ADM2 zip file to ADM4, and then edit the metadata accordingly.  You could do this in the same pull request if appropriate.

**Review by sylviashea1 — CHANGES_REQUESTED** [review]
The zipfile you uploaded only includes the shapefile. Please make sure it includes all additional files needed to support the shapefile.
Ultimately, this is what you need to do:
1. Delete the original ESP_ADM2.shp and ESP_ADM2.zip from your local repository.
2. Export the ESP_ADM2 on QGIS again, select all the files it spits out, and zip them into a zipfile named ESP_ADM2.zip. Then add to the gbOpen repository.
Push those changes and it should fix the problem!

**Review by slfuhrig — APPROVED** [review]
Everything looks great. Thanks for the revisions!

**Comment by DanRunfola** [comment]
This looks good - before I accept, next week I am going to use this PR to test a new github function that will allow some automatic programmatic checks for files as well (an "action").  I'll accept after that runs!

**Comment by DanRunfola** [comment]
Hey @MichaelR-geoLab - I went through your PR, and updated it to the new standard.  Last thing and we should be good to go.

**1) I attach two zips to this comment** - one of them is for gbOpen and the other gbAuthoritative.  On your computer, copy these into the gbOpen and gbAuthoritative files, respectively (basically, even though it's the same shapefile, we're duplicating).  Note they are different zips because they have different meta.txt files in them (one for gbOpen and one for gbAuthoritative)
gbOpen file:
[ESP_ADM2.zip](https://github.com/wmgeolab/gbRelease/files/5270397/ESP_ADM2.zip)

gbAuthoritative file:
[ESP_ADM2.zip](https://github.com/wmgeolab/gbRelease/files/5270403/ESP_ADM2.zip)

2) Delete gbOpenMetaData.csv, gbAuthoritativeMetaData.csv, and gbHumanitarianMetaData.csv .  We don't need these anymore, as the meta.txt in the zip will work now (woo!).

3) git add, git commit, and git push your changes.

And, that should be it! Once that happens the automated checks should run here, and we'll be ready to accept.  Note in the future, all you'll need to do is replace the zip files.

**Comment by MichaelR-geoLab** [comment]
Hey @DanRunfola , It looks like I did not quite follow your instructions correctly as GitHub still says there is a conflicting file, however I do not know what it wants from me nor what I did wrong, so if you, or someone else, has any clue, please let me know.

**Comment by DanRunfola** [comment]
Hey Michael -

Nope, you did it right!  That's just when two files collide.  I fixed it :).  Checks are running as I write this, will loop back when they finish (or you guys can take a look at the output).

**Comment by DanRunfola** [comment]
Hey MichaelR -
Sorry about this, but we did some big updates on our scripts to make submissions easier in the future.  Could you do one of the below:
1) Submit your file through the web interface - see https://youtu.be/9v5bZcpUx3I

or

2a) On your local client, Click on the 'current branch' tab and first select 'master' as the current branch (if it's not already selected).
2b)  Click on the 'fetch origin' button.
2c) Click on the 'current branch' tab again and click the 'choose a branch to merge into master' button at the bottom.
2d) Select upstream/master from this list, and this pull the changes down from the master repository to bring your local clone up to date.

Then, push your files back to this PR.  That will trigger the new checks, and make it so all your future desktop-based checks will work. Approach (1) is hopefully a much easier alternative (and why we did the upgrades).

**Pull request closed without merging**
