### PR TITLE
NPL_ADM1

### PR DESCRIPTION
**Pull request by jdturner303**
New pull request with correct file names. Includes updated shapefile.

## Checklist:

- [X] My submission is either a shapefile (with all the relevant files) or a geojson.
- [X] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [X] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [X] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — CHANGES_REQUESTED** [review]
We just need one tiny change! Everything has to be standardized across our boundaries, so please change the name of the "ISO" field to "ISO_Code."

**Comment by jdturner303** [comment]
I made the changes! Hopefully, it's good this time.

James Turner

**Review by slfuhrig — APPROVED** [review]
Perfect :)

**Comment by slfuhrig** [comment]
#678 has more detailed metadata.

**Pull request closed without merging**
