### PR TITLE
MDG_ADM3 Re-upload to fix issues Gitbot caught

### PR DESCRIPTION
**Pull request by MichaelR-geoLab**
release type was mislabeled as gBOpen when it should be Humanitarian

## Checklist:

- [x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x] I have included a file named "meta.txt", with all required metadata (see an example at https://bit.ly/2SAiWHk).
- [x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by sylviashea1** [comment]
Hey Michael! Is this for the metadata validation?

**Comment by MichaelR-geoLab** [comment]
Yes it is!

**Comment by sylviashea1** [comment]
Great! For the license.png screenshot, could you please retake it and include the address bar/URL? Otherwise, everything else is perfect.

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Great work, but please retake the license screenshot to include the URL. Everything else is great.

**Review by sylviashea1 — APPROVED** [review]
All files correct. Nice job! 👍

**Comment by DanRunfola** [comment]
:100: Thanks for the push, appreciated.

**Pull request merged**
