### PR TITLE
AZE_ADM0

### PR DESCRIPTION
**Pull request by taraamcl**
Meta data validation for AZE_ADM0

## Checklist:

- [X] My submission is either a shapefile (with all the relevant files) or a geojson.
- [X] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [X] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [X] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by slfuhrig** [comment]
You're failing the metadata check because your file isn't in the right place -- I'll help you fix it during office hours.

**Comment by taraamcl** [comment]
> Y

on zoom with lindsey now coming to OH later (((:

**Review by slfuhrig — APPROVED** [review]
Perfect!! Great job :)

**Comment by DanRunfola** [comment]
What does this one close?

**Comment by slfuhrig** [comment]
closes #389

**Comment by DanRunfola** [comment]
Thank you!!

**Comment by DanRunfola** [comment]
@all-contributors add @taraamcl  to data

**Pull request merged**
