### PR TITLE
KGZ_ADM2

### PR DESCRIPTION
**Pull request by SidonieH**
#114
Digitized CC map found on Wikipedia, made from existing KGZ_ADM0 gbOpen shapefile.

## Why do we need this boundary?  
https://github.com/wmgeolab/gbRelease/issues/114

## Anything Unusual?
There are some independent cities within Bishek City (which functions as an ADM1). These 4 would theoretically be ADM2 as well, but I was unable to find any boundaries for this. Therefore there is a hole in the data (in the North)

## Checklist:

- [ x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [ x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [ x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by SidonieH** [comment]
[KGZ_ADM2.zip](https://github.com/wmgeolab/gbRelease/files/5502563/KGZ_ADM2.zip)

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Great work! We just need a few small changes:
- in the metadata, please change source 1 to "geoBoundaries" and source 2 to the info you currently have in source 1, also make sure to fully write out the license (see if it matches one in the [list of licenses](https://github.com/wmgeolab/geoBoundaryBot/blob/master/dta/gbLicenses.csv) the bot will check, or we can get it added), and in the notes please say which ADM you digitized from :)
- in the attribute table, change level to be "ADM2", make sure the name field is called "Name", and make sure the ISO code field is called "ISO_Code" 

Let us know if you have any questions. The digitizing looks great!

**Comment by slfuhrig** [comment]
Will close #114

**Review by slfuhrig — APPROVED** [review]
Perfect

**Comment by slfuhrig** [comment]
Closes #114

**Comment by DanRunfola** [comment]
:rabbit: awesome, thank you!

**Comment by DanRunfola** [comment]
@all-contributors please add @SidonieH  for data

**Pull request merged**
