### PR TITLE
BDG_ADM2

### PR DESCRIPTION
**Pull request by helenabuckman**
Metadata validation: edited release type, checked license type, added canonical name, checked license source, added license.png

## Why do we need this boundary?  
Metadata validation 

## Checklist:

- [X] My submission is either a shapefile (with all the relevant files) or a geojson.
- [X] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [X] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [X] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — APPROVED** [review]
Great job!

**Comment by DanRunfola** [comment]
What issue is this for?

**Comment by slfuhrig** [comment]
Closes #264

**Review by slfuhrig — APPROVED** [review]

**Comment by DanRunfola** [comment]
:+1: thank you!

**Pull request merged**
