### PR TITLE
FRA ADM 5

### PR DESCRIPTION
**Pull request by memulder**
## Why do we need this boundary?  
 Issue #166 

## Checklist:

- [ x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example at https://bit.ly/2SAiWHk).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — DISMISSED** [review]
I think everything with FRA_ADM5 looks good even though it's still failing checks

**Comment by DanRunfola** [comment]
Ok - the issue is because this PR has a deletion and an addition for different countries.  I.e., it's adding FRA 5 and also asking to delete CIV0.  So, the bot is being confused, as it can't download anything for CIV0, because it doesn't exist.

**Review by DanRunfola — CHANGES_REQUESTED** [review]
Ok - the issue is because this PR has a deletion and an addition for different countries. I.e., it's adding FRA 5 and also asking to delete CIV0. So, the bot is being confused, as it can't download anything for CIV0, because it doesn't exist.

**Comment by sylviashea1** [comment]
FRA_ADM5 will be pushed by Dan. Instructions on LFS PRs to come.

**Pull request closed without merging**
