### PR TITLE
PNG_ADM1 GbOpen

### PR DESCRIPTION
**Pull request by iaschreur**
## Why do we need this boundary?  
#384

## Checklist:

- [ x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [ x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [ x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [ x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — CHANGES_REQUESTED** [review]
So close! I went ahead and looked through your submission and everything is perfect. I'm not sure why your metadata check is failing -- try making a new file and manually entering the info in the fields (it could be a formatting error).

**Review by slfuhrig — APPROVED** [review]
Perfect!

**Comment by slfuhrig** [comment]
closes #384

**Comment by DanRunfola** [comment]
Not sure on the metadata issue either - I'm going to look into that a bit further.

**Comment by DanRunfola** [comment]
@all-contributors add @iaschreur  to data

**Pull request merged**
