### PR TITLE
MEX_ADM0

### PR DESCRIPTION
**Pull request by larogersWM**
Found new open file for ADM0 (dissolved from ADM2)

## Checklist:

- [X] My submission is either a shapefile (with all the relevant files) or a geojson.
- [X] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [X] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [X] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by nmspage — CHANGES_REQUESTED** [review]
One quick fix! Please make sure there are three fields named "Name", "ISO", and "Level"

**Comment by slfuhrig** [comment]
"ISO_Code" instead of "ISO" for that field.

**Review by nmspage — APPROVED** [review]
Looks perfect! Closes #669 and #460

**Comment by DanRunfola** [comment]
:mexico: :mexico: :mexico:

**Comment by DanRunfola** [comment]
:mexico: :mexico: :mexico: 
(Double prizes since this closed two issues)

**Pull request merged**
