### PR TITLE
PSE_ADM0 446

### PR DESCRIPTION
**Pull request by slfuhrig**
## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [ x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by nmspage** [comment]
Closes issue #446

**Review by nmspage — CHANGES_REQUESTED** [review]
There is an extra folder with another png license and meta that should be removed. Almost there!

**Review by nmspage — CHANGES_REQUESTED** [review]
Hmm, the file _MACOSX still seems to be in the zipfile

**Review by nmspage — APPROVED** [review]
All seems to be clear, and the file present will not disrupt the code.

**Comment by DanRunfola** [comment]
Yeah, the macos folder is OK.  We'll clean those up in builds.

**Pull request merged**
