### PR TITLE
KOR_ADM2

### PR DESCRIPTION
**Pull request by dorianvmiller**
Metadata validation for KOR_ADM2 - had to find new shapefile, original license not valid for gbOpen.

## Why do we need this boundary?  
 #428 

## Checklist:

- [ x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [ x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [ x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — CHANGES_REQUESTED** [review]
Everything looks great! Can you try to find the names in a Roman alphabet? If you have any problems with that, don't hesitate to reach out.

**Comment by dorianvmiller** [comment]
Resubmitted with the names in the Roman alphabet, luckily the original dataset included both.

**Review by slfuhrig — APPROVED** [review]
Perfect! I'm glad it was an easy fix.

**Comment by DanRunfola** [comment]
:kr: :kr: :kr:

**Pull request merged**
