### PR TITLE
NGA_ADM1 reuploaded with new process

### PR DESCRIPTION
**Pull request by larogersWM**
#112 Reuploaded with new process

## Checklist:

- [X] My submission is either a shapefile (with all the relevant files) or a geojson.
- [X] I have included a file named "meta.txt", with all required metadata (see an example at https://bit.ly/2SAiWHk).
- [X] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [X] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by DanRunfola** [comment]
Ah, you Mac OS people.  There was a folder inside your zipfile called "_MACOSX", which had some misc. metadata from your mac (including copies of shapefiles).  You probably don't even see it by default.  I'll be cleaning it up in the postprocessing anyway, so I'm going to tweak the bot to ignore it and will re-run shortly after.

**Comment by DanRunfola** [comment]
Ok - last bot run is correct, and I am now ignoring the mac metadata pieces.

Looks like all that you have wrong is "Creative Commons Attribution 4.0 (CC-BY 4.0)"

Needs to be "Creative Commons Attribution 4.0 (CC BY 4.0)" (no dash).

**Review by sylviashea1 — APPROVED** [review]
Metadata fixed and all shapefile parts look good! Nice job.

**Comment by sylviashea1** [comment]
This shapefile replaces NGA_ADM1 in gbOpen master. Now has meta.txt and license.png. Addresses #112

**Review by slfuhrig — APPROVED** [review]
Great work!

**Comment by slfuhrig** [comment]
Related to issue #112 - reuploaded to test new upload methodology.

**Comment by DanRunfola** [comment]
:100:

**Pull request merged**
