### PR TITLE
gbHumanitarian MRT ADM 2 metadata validation

### PR DESCRIPTION
**Pull request by carolinamonrivera**
Validated the license and source, added the canonical name for boundary and added license.png. The issue is  #330.

## Why do we need this boundary?  
https://github.com/wmgeolab/gbRelease/issues/330

## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example at https://bit.ly/2SAiWHk).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by slfuhrig** [comment]
Please change the release type to "gbHumanitarian"

**Comment by DanRunfola** [comment]
Screenshot from 2020-10-12 11-28-23

Looks like you have a folder in your zip file ("MRT_ADM2").  No folders - just put everything right in the root of the zip.

Recognizing this is inconvenient; I'm working on logic for the bot to be able to detect things nested in folders, but it will be a bit (..like a year ;) ).

**Review by slfuhrig — DISMISSED** [review]
Looks great to me! I think the duplicate has been deleted.

**Review by DanRunfola — CHANGES_REQUESTED** [review]
This is so close :).  Just a duplicate that needs to be removed.

**Comment by slfuhrig** [comment]
Addressed by PR #524

**Comment by DanRunfola** [comment]
@all-contributors please add @slfuhrig for review

**Pull request closed without merging**
