### PR TITLE
NER_ADM2

### PR DESCRIPTION
**Pull request by carolinamonrivera**
gbHumanitarian MRT ADM 2 metadata validation #330

Validated release, source and added license.png.

## Why do we need this boundary?  
https://github.com/wmgeolab/gbRelease/issues/329

## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example at https://bit.ly/2SAiWHk).
- [x ] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x ] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — APPROVED** [review]
I think everything looks good even though all checks haven't passed.

**Comment by DanRunfola** [comment]
The errors here are coming because you've pushed two files into the PR, instead of just one.  Delete the erroneous one and I think this will be ready to go.

**Review by DanRunfola — CHANGES_REQUESTED** [review]
The errors here are coming because you've pushed two files into the PR, instead of just one. Delete the erroneous one and I think this will be ready to go.

**Review by slfuhrig — CHANGES_REQUESTED** [review]
The release type and other notes fields are what's causing you to fail the metadata check.

**Comment by slfuhrig** [comment]
Replaced with #536

**Pull request closed without merging**
