### PR TITLE
GIN_ADM0

### PR DESCRIPTION
**Pull request by dorianvmiller**
Metadata validation for GIN_ADM0

 GIN_ADM0

## Why do we need this boundary?  
 #289 

## Checklist:

- [ x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [ x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [ x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [ x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Review by slfuhrig — CHANGES_REQUESTED** [review]
So close!

We need some metadata changes:

source 1 needs to be "geoBoundaries" since we derived the file from another layer aka edited the shapefile

source 2 needs to be what you currently have listed for source 1

describe how the file was derived from ADM3 in the "Other Notes" field

**Review by sylviashea1 — APPROVED** [review]
Implemented all changes, nice job!

**Comment by dorianvmiller** [comment]
Changes have been implemented but it looks like it still requires another review - commenting to make sure the bot doesn't close this!

**Review by slfuhrig — APPROVED** [review]
Perfect! Thanks for the comment reminding me to check this out :)

**Comment by DanRunfola** [comment]
Good job stale bot!  And thanks all :)

**Pull request merged**
