### PR TITLE
GHA_ADM0

### PR DESCRIPTION
**Pull request by dorianvmiller**
GHA_ADM0 with license for gbOpen
https://github.com/wmgeolab/gbRelease/issues/90

 GHA_ADM0

## Why do we need this boundary?  
 https://github.com/wmgeolab/gbRelease/issues/90

## Checklist:

- [x ] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [ x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [ x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by sylviashea1** [comment]
meta.txt is included in root directory, but bot can't find it.

**Review by sylviashea1 — CHANGES_REQUESTED** [review]
Hey Dorian! Please do the following before re-submitting the PR:
1. Make sure all supporting file types are present before zipping the shapefile (I believe you're missing .sbn and .shp.xml). If needed, re-export the feature in QGIS to get all needed files.
2. Once you have all your files (including meta and license), select them and compress them. Do not compress the folder that they're in (I'd encourage you to do it on your Desktop to avoid confusion). This will hopefully remove the problem of a subfolder in your submission. 
Thanks :)

**Review by sylviashea1 — APPROVED** [review]
YES! Nice job, Dorian!

**Comment by slfuhrig** [comment]
Closes #90

**Comment by DanRunfola** [comment]
Great, thank you for the submission.

**Pull request merged**
