### PR TITLE
CAF_ADM0,1,2

### PR DESCRIPTION
**Pull request by dorianvmiller**
Found new source and digitized layer for CAF_ADM2, metadata validation for CAF_ADM0-1

## Checklist:

- [x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by dorianvmiller** [comment]
This PR is for #61 which has a couple of things going on, here's some clarification:
- Metadata validation for ADM0 and ADM1
- Found new source for ADM2. I couldn't find a shapefile anywhere so I used a pdf map I found and georeferenced and digitized it. Let me know if you find any issues with it!
- New source for ADM3. I looked for one for a while and couldn't find a map or shapefile for ADM3 except for the original humdata source which does not work for gbOpen. Maybe make a new issue for just ADM3 (not sure if that's out there)?

**Comment by dorianvmiller** [comment]
This PR is for #61 which has a couple of things going on, here's some clarification:
- Metadata validation for ADM0 and ADM1
- Found new source for ADM2. I couldn't find a shapefile anywhere so I used a pdf map I found and georeferenced and digitized it. Let me know if you find any issues with it!
- New source for ADM3. I looked for one for a while and couldn't find a map or shapefile for ADM3 except for the original humdata source which does not work for gbOpen. Maybe make a new issue for just ADM3 (not sure if that's out there)?

**Review by slfuhrig — APPROVED** [review]
Excellent job on ADM2 - great digitization.

**Comment by DanRunfola** [comment]
Wow, nice PR.  Thanks for packaging all of this together.

**Pull request merged**
