### PR TITLE
GAB_ADM2

### PR DESCRIPTION
**Pull request by jrhabib**
Issue number 86

## Checklist:

- [ X] My submission is either a shapefile (with all the relevant files) or a geojson.
- [X ] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [ X] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [ X] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

### CODE REVIEW

**Comment by sylviashea1** [comment]
Bot states that "Other - Direct Permission" is not a compatible license type for gbOpen, but it's listed as one in the bot specs. One issue may be that there's no URL for license source, but that check passed. Not sure what the deal is.

**Comment by sylviashea1** [comment]
@DanRunfola when you can, please check out the weird issue with license described above.

**Comment by sylviashea1** [comment]
@DanRunfola Please double check the licensing issue ;)

**Review by sylviashea1 — APPROVED** [review]
Nice work!

**Comment by DanRunfola** [comment]
Evenutally we'll move away from Direct Permission, but this is suitable for now.  Thank you!

**Comment by DanRunfola** [comment]
@all-contributors please add @jrhabib  for data

**Pull request merged**
